//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_commerce_ef
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ordersEntities : DbContext
    {
        public ordersEntities()
            : base("name=ordersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<orderitem> orderitems { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<utenti> utentis { get; set; }
    }
}
